# Quarkus Picocli configuration
quarkus.banner.enabled=false
quarkus.log.level=WARN
quarkus.log.category."sh.skills".level=INFO

# Native image
quarkus.native.resources.includes=**/*.json,**/*.properties
